### ISSUE TITLE
SyntaxError while building with Python 2.7.5

### ISSUE THREAD

**Issue by smoretti** [testing-cabal/linecache2#12]
Hi

I have an issue while installing the library with Python 2.7.5 (It if fine with Python 3.4.1).
setup.py build step looks fine but setup.py install step returns this error:

>   File "/software/lib/python2.7/site-packages/linecache2/tests/inspect_fodder2.py", line 102
>     def keyworded(*arg1, arg2=1):
>                             ^
> SyntaxError: invalid syntax

**Comment by prat0318** [comment]
Same here.

**Comment by jenisys** [comment]
That happens also for me when I try to install my package with ``python setup.py install`` that indirectly depends on ``linecache2`` (via ``traceback2``) and ``linecache2`` is not installed yet. This is a major annoyance.

NOTE: This problem does not occur when everything is installed with pip.

**Comment by rbtcollins** [comment]
This is happening in the precompilation of .pyc files and should be entirely harmless.

**Comment by jenisys** [comment]
Sorry, I disagree. It causes certain package installation scenarios to fail.

**Comment by rbtcollins** [comment]
Please provide more details then.

**Comment by jenisys** [comment]
I must correct myself. This was a major nuisance in the past because it prevented me from installing my project which depended on ``traceback2`` which depended on ``linecache2``. I always needed manual steps to overcome the problem. As stated above installation of the source package caused the problem. Fixes around pip, setuptools, wheel, etc. seem to have solved this problem.

Now it just looks bad when you see errors during the installation process of a package. It makes me normally think that the project/package maintainer does not care about the provided package.

**Comment by rbtcollins** [comment]
I can understand that; however the issue here is that thsi is a test file that we need to introspect python3 features, so it literally cannot be compatible with python2. Its not loaded at runtime, and is only tested conditionally on python3.
